задание 4 2-й раздел
js-tasks-ru/vue-20221107_aleksey-reshetilo pull request #4
Opened 2022-11-25 22:30 UTC by eldenhard

2022-11-25 22:31 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-11-27 20:06 UTC, ShGKme requested changes
В `01-basics/04-MeetupTitle` требуются небольшие изменения. Кроме того, удаление задачи не считается за её решение :)

Могу помочь, если нужна помощь с решением задачи

2022-11-27 20:06 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +    }
При решении требуется использовать функцию `fetchMeetupById`. Она корректно работает и её редактирование не должно быть необходимо для её использовании во Vue приложении.

2022-11-27 20:06 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
>          throw error;
Изменять функцию не требуется. Она не связана с компонентом и решает одну задачу - получение митапа с API.

2022-12-02 07:54 UTC, eldenhard commented on 01-basics/04-MeetupTitle/script.js
>          throw error;
Здравствуйте, натолкните тогда пожалуйста на иное решение

2022-12-02 15:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-03 21:46 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-06 19:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-06 19:54 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +  },
Функция `icon` ничего не возвращает. Потерялся `return`.

2022-12-06 19:54 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <h3 class="agenda-item__title" v-else>{{agendaItem.title}}</h3>
Заголовок по умолчанию можно вычислять также, как вычисляется `icon`.

2022-12-06 19:54 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +        <h3 class="agenda-item__title" v-else>{{agendaItem.title}}</h3>
Вместо `v-if="X != null"` лучше сделать `v-if="X"`. Нестрогое сравнение работает не очень очевидно. Например, `undefined` тут пройдёт, а пустая строка не пройдёт. Проверка на `v-if="X"` пропустит все не falsy значения.

2022-12-06 19:54 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
>          </p>
Весь целиком этот блок (`agenda-item__talk`) должен выводиться только, если тип пункта программы - `agendaItem.type === 'talk'`.

2022-12-06 19:54 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgenda.js
>      </ul>`,
Здесь в комментарии выводился компонент для одного пункта программы `<MeetupAgendaItem />`. Но ему не передаётся сам пункт программы, который он должен выводить. Пункт программы должен передаваться в параметр `agendaitem`. При этом выводить надо этот компонент для каждого пункта (для каждого элемента массива `agenda`).

2022-12-08 08:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-08 08:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-08 08:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-10 16:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-10 16:39 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-12 18:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-12-12 19:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-13 13:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-13 13:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-13 14:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-12-14 20:46 UTC, ShGKme approved these changes
Все задачи приняты

2022-12-14 20:46 UTC, ShGKme commented on 02-components/06-MeetupView/components/MeetupView.js
> +import MeetupInfo from '../components/MeetupInfo'
В путях можно не возвращаться обратно, чтобы зайти в ту же директорию.
Находясь в директории `components` пусть `../components/MeetupCover.js` тоже самое что `./MeetupCover.js`. Аналогично с остальными импортами

2022-12-14 20:47 UTC, merged